"""Translations and app settings."""

APP_VERSION = "v2.3.6 Pro — AI Settings Manager"
MAX_HISTORY = 10
MAX_UPLOAD_SIZE_MB = 100
MAX_HISTORY_MEM_MB = 500
USERS_FILE = "users.json"


def get_appdata_dir() -> str:
    """Writable per-user directory for DataBridge runtime files."""
    import os
    base = os.environ.get("APPDATA") or os.path.join(os.path.expanduser("~"), ".databridge")
    path = os.path.join(base, "DataBridge") if os.environ.get("APPDATA") else base
    os.makedirs(path, exist_ok=True)
    return path


def get_config_path() -> str:
    import os
    return os.path.join(get_appdata_dir(), "config.json")


def load_config() -> dict:
    import json, os
    path = get_config_path()
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            if isinstance(data, dict):
                data.setdefault("ai_provider", "gemini")
                data.setdefault("gemini_model", "gemini-2.5-flash")
                data.setdefault("gemini_api_key", "")
                return data
            return {"ai_provider": "gemini", "gemini_model": "gemini-2.5-flash", "gemini_api_key": ""}
        except Exception:
            pass
    return {"ai_provider": "gemini", "gemini_model": "gemini-2.5-flash", "gemini_api_key": ""}


def save_config(cfg: dict) -> None:
    import json
    path = get_config_path()
    with open(path, "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)


T = {
    "ar": {
        "app_name": "DataBridge",
        "app_sub": "M&E Hub for Health Programs",
        "app_slogan": "منصة المتابعة والتقييم المتكاملة",
        "login_title": "تسجيل الدخول",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "login_btn": "دخول",
        "login_error": "❌ اسم المستخدم أو كلمة المرور غلط",
        "logout": "تسجيل خروج",
        "upload_label": "ارفع ملف IDUs Database (Excel)",
        "upload_hint": "📋 ارفع ملف IDUs Database وهيتحلل تلقائياً",
        "upload_hint2": "✅ البرنامج عارف هيكل الشيت وهيحلل الفراغات المنطقية تلقائياً",
        "tab_data": "📋 البيانات",
        "tab_gaps": "🔍 تحليل الفراغات",
        "tab_stats": "📊 الإحصائيات",
        "tab_export": "💾 التصدير",
        "total": "إجمالي المستفيدين",
        "has_followup": "لديهم متابعة",
        "no_followup": "بدون متابعة",
        "positive": "نتيجة إيجابية",
        "refused": "رفضوا التحليل",
        "beneficiary": "مستفيد",
        "positive_case": "حالة إيجابية",
        "from_total": "من الإجمالي",
        "show_label": "عرض:",
        "all_data": "كل البيانات",
        "without_followup": "بدون متابعة",
        "with_followup": "مع متابعة",
        "positive_cases": "الحالات الإيجابية",
        "rows_count": "عدد الصفوف",
        "gaps_info": "الفراغات دي مش غلط — كل فراغ ليه سبب منطقي موضح أدناه",
        "gaps_report": "تقرير الفراغات",
        "no_gaps": "✅ لا توجد فراغات!",
        "col_name": "العمود",
        "gap_count": "عدد الفراغات",
        "gap_pct": "نسبة %",
        "gap_reason": "سبب الفراغ المنطقي",
        "gap_status": "الحالة",
        "justified": "✅ مبرر منطقياً",
        "needs_review": "⚠️ يحتاج مراجعة",
        "export_csv": "📥 تصدير CSV",
        "export_excel": "📥 تصدير Excel مع التقرير",
        "save_excel_title": "💾 حفظ في شيت Excel",
        "upload_db": "ارفع ملف IDUs Database Excel",
        "save_all_btn": "✅ أضف كل السجلات للشيت",
        "save_success": "تم الحفظ بنجاح!",
        "download_updated": "⬇️ حمّل الشيت المحدّث",
        "chart_test": "نتائج التحليل",
        "chart_followup": "توزيع المتابعة",
        "chart_services": "الخدمات المقدمة (من تلقوا الخدمة فعلاً)",
        "chart_age": "توزيع الفئات العمرية",
        "chart_area": "التوزيع الجغرافي — منطقة الوصول",
        "chart_gov": "توزيع المحافظات",
        "chart_age_prot": "أدوات الوقاية حسب الفئة العمرية",
        "chart_monthly": "الزيارات الشهرية",
        "with_followup_label": "مع متابعة",
        "without_followup_label": "بدون متابعة",
        "refused_test": "رفض التحليل",
        "file_error": "خطأ في تحميل الملف",
        "lang_btn": "English",
        "section_title": "IDUs Database — Be Frienders 2026",
        "col_reason_confirm": "التحليل سلبي أو لم يُجرَ تحليل",
        "col_reason_referral": "التحليل سلبي أو لم يُجرَ تحليل",
        "col_reason_test_fu": "لا توجد متابعة أو لم يُجرَ تحليل",
        "col_reason_condoms_fu": "لا توجد متابعة",
        "col_reason_lube_fu": "لا توجد متابعة",
        "col_reason_syph_fu": "رفض المستفيد أو لا توجد متابعة",
        "col_reason_psycho_fu": "رفض المستفيد أو لا توجد متابعة",
        "col_reason_syr_fu": "لا توجد متابعة",
        "col_reason_meth_fu": "رفض المستفيد أو لا توجد متابعة",
        "col_reason_default": "رفض المستفيد",
        # ── Phase 2 ──
        "tab_quality": "🔎 جودة البيانات",
        "dq_title": "محرك جودة البيانات",
        "dq_subtitle": "فحص شامل لكل سجل وفق القواعد المنطقية المعتمدة",
        "dq_errors": "خطأ جودة بيانات",
        "dq_warnings": "تحذير",
        "dq_ok": "سجل صحيح",
        "dq_col_row": "رقم السجل",
        "dq_col_field": "الحقل",
        "dq_col_value": "القيمة",
        "dq_col_rule": "القاعدة المنتهكة",
        "dq_col_severity": "الخطورة",
        "dq_col_notes": "ملاحظات",
        "dq_save_notes": "💾 حفظ الملاحظات",
        "dq_notes_saved": "✅ تم حفظ الملاحظات",
        "dq_export": "📥 تصدير تقرير الجودة",
        "dq_filter_label": "فلتر حسب الخطورة:",
        "dq_all": "الكل",
        "dq_err_age": "العمر خارج النطاق المسموح (15-70 أو فئات محددة)",
        "dq_err_age_u15": "عمر أقل من 15 — يلزم ملاحظة ولي الأمر",
        "dq_err_positive_referral": "نتيجة إيجابية بدون إحالة للعلاج",
        "dq_err_followup_nodate": "توجد بيانات متابعة بدون تاريخ متابعة",
        "dq_err_negative_qty": "كمية سالبة غير مقبولة",
        "dq_err_duplicate_serial": "رقم مسلسل مكرر",
        "dq_err_duplicate_code": "كود مجمع مكرر",
        "dq_err_code_mismatch": "الكود المجمع لا يطابق بيانات تاريخ الميلاد أو المحافظة",
        "dq_warn_positive_noconfirm": "نتيجة إيجابية بدون تحليل تأكيدي (نادر — قد يكون رفض المستفيد)",
        "dq_err_invalid_code_format": "تنسيق الكود المجمع غير صحيح",
        "dq_notes_placeholder": "أضف ملاحظة...",
        "dq_no_issues": "✅ لا توجد مشاكل في جودة البيانات!",
        "dq_run_btn": "🔍 تشغيل فحص الجودة",
        "dq_show_errors_only": "🔴 الأخطاء فقط",
        "dq_show_warnings_only": "🟡 التحذيرات فقط",
        "dq_show_all_issues": "كل المشاكل",
        "dq_records_with_issues": "سجلات بها مشاكل",
        # ── Phase 3 — Full bilingual sweep ──
        # Password change
        "change_password_btn": "🔑 تغيير كلمة المرور",
        "current_password": "كلمة المرور الحالية",
        "new_password": "كلمة المرور الجديدة",
        "confirm_password": "تأكيد كلمة المرور",
        "save_btn": "حفظ",
        "password_mismatch": "❌ كلمة المرور الجديدة غير متطابقة",
        "pw_current_wrong": "❌ كلمة المرور الحالية غير صحيحة",
        "pw_new_too_short": "❌ كلمة المرور الجديدة يجب أن تكون 8 أحرف على الأقل",
        "pw_new_same_as_old": "❌ كلمة المرور الجديدة يجب أن تختلف عن القديمة",
        "pw_changed_success": "✅ تم تغيير كلمة المرور بنجاح",
        # Source auto-converter (upload + 204-col converter)
        "err_not_204_sheet": "هذا الملف لا يبدو الشيت الأساسي 204 عمود.",
        "err_no_visit_date_or_code": "لم يتم العثور على تاريخ الزيارة أو الكود المجمع داخل الشيت الأساسي.",
        "convert_upload_hint": "🔄 ارفع الشيت الأساسي (204 عمود) وسيتحول تلقائياً إلى هيكل شيت البرنامج",
        "converting_spinner": "⚙️ جاري التحويل...",
        "converted_prefix": "[محوّل]",
        "convert_success": "تم التحويل!",
        "convert_success_records": "سجل جاهز للتحليل",
        "download_converted_sheet": "⬇️ تحميل الشيت المحوّل",
        "auto_converted_detected": "🔄 تم اكتشاف الشيت الأساسي 204 عمود وتحويله تلقائيًا قبل التحليل.",
        "converted_auto_prefix": "[محوّل تلقائي]",
        # Smart Data Cleaner / Auto Mapper
        "smart_cleaner_title": "Smart Data Cleaner — فحص وتنظيف الملف",
        "mapper_confidence_title": "Auto Data Mapper — لوحة الثقة قبل الاعتماد",
        "mapper_verify_sub": "85–94% غالبًا صحيح",
        "mapper_suspicious_sub": "70–84% يحتاج انتباه",
        "mapper_unknown_sub": "أقل من 70%",
        "mapper_profile_warning": "Data Profile Validation اكتشف ربطًا مشكوكًا فيه بناءً على محتوى الأعمدة، وليس الاسم فقط.",
        "mapper_report_title": "Auto Data Mapper — تقرير ربط الأعمدة",
        "mapper_profile_caption": "عند الاعتماد سيتم حفظ الربط في AppData/DataBridge/mapping_memory.json لاستخدامه في المرات القادمة.",
        "mapper_approved_success": "✅ تم اعتماد ربط الأعمدة وحفظه في Mapping Memory. يمكنك الاعتماد على التحليل الحالي.",
        "mapper_unapprove_btn": "↩️ إلغاء الاعتماد وإعادة المراجعة",
        "mapper_review_warning": "راجع ربط الأعمدة أولًا، ثم اضغط اعتماد قبل ظهور التحليل والرسومات.",
        "mapper_approve_btn": "✅ اعتماد الربط وتشغيل التحليل",
        "mapper_approve_btn_with_review": "✅ اعتماد الربط رغم وجود",
        "cleaner_missing_core_error": "فيه أعمدة أساسية ناقصة. راجع التقرير قبل الاعتماد على الأرقام.",
        "cleaner_warnings_warning": "تم تنظيف الملف، لكن فيه تحذيرات قد تؤثر على فلاتر الشهر أو بعض الرسومات.",
        "cleaner_success": "تم تنظيف الملف وتجهيزه للتحليل بنجاح.",
        "analysis_paused_info": "⏸️ التحليل متوقف مؤقتًا لحين اعتماد ربط الأعمدة من تقرير Auto Data Mapper بالأعلى.",
        # Records-displayed info box
        "records_displayed": "السجلات المعروضة",
        "of_total": "من إجمالي",
        # Compact summary table labels
        "tbl_count": "العدد",
        "tbl_reach": "الوصول",
        "tbl_men": "رجال",
        "tbl_followup": "متابعه",
        "tbl_syringes": "سرنجات",
        "tbl_followup_syringes": "سرنجات متابعه",
        "tbl_lubricants": "مزلقات",
        "tbl_followup_lubricant": "متابعه مزلق",
        "tbl_condoms": "واقيات",
        "tbl_followup_condom": "متابعة واق",
        "tbl_total_tests": "اجمالي التحاليل",
        "tbl_negative": "سلبي",
        "tbl_positive": "ايجابي",
        "tbl_not_available": "غير متوفر",
        "tbl_confirmatory_positive": "ايجابي تأكيدي",
        "tbl_psycho_support": "دعم نفسي",
        "tbl_syphilis": "زهري",
        "tbl_item": "البيان",
        # Summary tab labels
        "summary_tab_month_prefix": "📋 ملخص شهر",
        "summary_tab_default": "📋 ملخص البيانات",
        # Tab names
        "tab_repair": "🛠 مركز إصلاح البيانات",
        "tab_indicators": "📈 المؤشرات",
        "tab_ai": "🤖 المساعد الذكي",
        "tab_settings": "⚙️ الإعدادات",
        "tab_converter": "🔄 تحويل الشيت",
        # Chart axis/legend labels
        "chart_label_result": "النتيجة",
        "chart_label_count": "العدد",
        "chart_label_status": "الحالة",
        "chart_label_service": "الخدمة",
        "chart_label_age_group": "الفئة العمرية",
        "chart_label_area": "المنطقة",
        "chart_label_governorate": "المحافظة",
        "chart_label_tool": "الأداة",
        "chart_label_month": "الشهر",
        "chart_label_visit_count": "عدد الزيارات",
        # Service/intervention category labels (chart series names)
        "svc_syphilis": "زهري",
        "svc_psycho_support": "دعم نفسي",
        "svc_methadone": "ميثادون",
        "svc_condoms": "واقيات",
        "svc_lubricants": "مزلقات",
        "svc_syringes": "سرنجات",
        # Period / export labels
        "period_to": "إلى",
        "period_all": "كل الفترة",
        "period_summary_caption": "ملخص الفترة",
        "download_summary_excel": "⬇️ تحميل ملخص البيانات Excel",
        "summary_filename_prefix": "ملخص_البيانات",
        # Data Quality tab
        "dq_running_spinner": "🔍 جاري الفحص...",
        "dq_run_prompt": "اضغط زر الفحص لتشغيل محرك جودة البيانات على {n} سجل",
        "dq_total_issues": "إجمالي المشاكل",
        "dq_col_serial": "مسلسل",
        "dq_under15_notice": "🔴 السجلات التالية تحتاج ملاحظة ولي الأمر:",
        "dq_record_label": "سجل #{row} — مسلسل {serial} — عمر: {age}",
        "dq_severity_error": "خطأ",
        "dq_severity_warning": "تحذير",
        "dq_download_report": "⬇️ تحميل تقرير الجودة",
        # Indicators tab
        "indicators_subtitle": "الإنجاز الفعلي للمؤشرات البرامجية",
        "targets_subtitle": "أدخل المستهدفات من Global Fund — Annual + Q1/Q2/Q3/Q4",
        # Reports / AI Assistant tab
        "generating_reports_spinner": "⚙️ جاري إنشاء التقارير...",
        "download_report_ar": "⬇️ التقرير العربي (.docx)",
        "download_report_en": "⬇️ التقرير الإنجليزي (.docx)",
        "reports_generated_success": "✅ تم إنشاء التقريرين!",
        "ai_assistant_subtitle": "مساعد ذكي متخصص في M&E — يكتب تقارير ويحلل البيانات",
        # Settings tab
        "settings_subtitle": "إعدادات البرنامج — تُحفظ تلقائياً في AppData / DataBridge",
        "get_free_key_from": "احصل على مفتاحك المجاني من:",
        "settings_saved_in": "الإعدادات تُحفظ في:",
        "api_key_saved": "✅ مفتاح محفوظ",
        "ai_provider_help": "حالياً Gemini فقط، ويمكن إضافة OpenAI أو Local LLM لاحقاً.",
        "fallback_model_warning": "⚠️ الموديل المختار غير متاح، لكن الاتصال نجح باستخدام fallback: {model}",
        "model_not_available_error": "❌ الموديل غير متاح. جرّب اختيار موديل آخر من الإعدادات.",
        "app_info_title": "معلومات البرنامج",
        # Source Converter tab
        "converter_tab_subtitle": "تحويل الشيت الأساسي (204 عمود) إلى شيت البرنامج (27 عمود) تلقائياً",
        "converter_tab_hint": "ارفع الشيت الأساسي (المكوّن من 204 عمود) وسيتحول تلقائياً إلى هيكل شيت البرنامج جاهزاً للتحليل.",
        "upload_source_sheet_excel": "ارفع الشيت الأساسي (Excel)",
        "file_label": "الملف",
        "columns_label": "عمود",
        "convert_now_btn": "🔄 تحويل الآن",
        "convert_clean_success": "تم التحويل والتنظيف!",
        "convert_clean_records": "سجل",
        "converter_auto_mapper_title": "Auto Mapper للملف المحوّل — راجع الربط قبل الاعتماد",
        "use_converted_btn": "✅ استخدام الملف المحوّل في التحليل وفتح شاشة الاعتماد",
        "convert_error": "خطأ في التحويل",
        # Data Repair Center
        "data_updated_info": "تم تحديث البيانات داخل الجلسة. سيتم إعادة تحميل التحليل الآن.",
        "repair_center_title": "🛠 مركز إصلاح البيانات",
        "repair_caption": "كل الإصلاحات هنا تحتاج موافقتك. لا يتم تنفيذ أي Fill أو تخمين تلقائي على الملف بالكامل.",
        "repair_no_examples": "✅ لا توجد أمثلة أخطاء واضحة في التواريخ/الكميات/نعم-لا.",
        "repair_no_suggestions": "لا توجد إصلاحات مقترحة حاليًا.",
        "repair_forbidden_warning": "🚫 ممنوع الإصلاح التلقائي للحقول الحساسة: Visit Date / Follow-up Date / HIV Result / Referral / Gender / Age / Beneficiary Code. التواريخ يتم تحويل القابل للقراءة فقط بدون ملء أو تخمين.",
        "repair_applied_success": "✅ تم تنفيذ الإصلاحات المختارة فقط.",
        # data_cleaner.py report tables
        "rpt_col_check": "الفحص",
        "rpt_col_result": "النتيجة",
        "rpt_col_type": "النوع",
        "rpt_check_status": "حالة الفحص",
        "rpt_detected_sheet": "الشيت المكتشف",
        "rpt_first_or_selected": "الأول/المحدد",
        "rpt_rows_before": "الصفوف قبل التنظيف",
        "rpt_cols_before": "الأعمدة قبل التنظيف",
        "rpt_rows_after": "الصفوف بعد التنظيف",
        "rpt_cols_after": "الأعمدة بعد التنظيف",
        "rpt_memory_usage": "استهلاك الذاكرة MB",
        "rpt_detected_header_row": "صف العناوين المكتشف",
        "rpt_sheet_ranking": "ترتيب الشيتات",
        "rpt_mapping_result": "نتيجة Auto Mapping",
        "rpt_missing_core_cols": "أعمدة أساسية ناقصة",
        "rpt_missing_optional_cols": "أعمدة مهمة غير موجودة",
        "rpt_invalid_dates_in": "تواريخ غير صالحة في {col}",
        "rpt_negative_qty_in": "كميات سالبة/غير منطقية في {col}",
        "rpt_empty_rows_dropped": "صفوف فارغة تم حذفها",
        "rpt_standard_df_summary": "{rows} صف × {cols} عمود",
        "rpt_note": "ملاحظة",
        "rpt_col_original": "العمود الأصلي",
        "rpt_col_canonical": "العمود القياسي",
        "rpt_col_confidence": "الثقة",
        "rpt_col_method": "الطريقة",
        # data_cleaner.py dynamic notes/warnings/errors
        "msg_high_memory": "استهلاك الذاكرة عالي؛ قد تكون الرسومات والتصدير أبطأ من المعتاد.",
        "msg_incomplete_analysis": "التحليل قد يكون غير كامل بسبب نقص أعمدة أساسية.",
        "msg_dates_converted_blank": "تم تحويل التواريخ غير الصالحة إلى فراغ، ولن تدخل في فلاتر الشهر.",
        "msg_qty_converted_blank": "تم تحويل الكميات غير الرقمية إلى فراغ، والكميات السالبة موضحة في التقرير.",
        "msg_profile_validation_suspicious": "Data Profile Validation اكتشف ربطًا مشكوكًا فيه بناءً على محتوى الأعمدة.",
        "msg_mapping_needs_review": "فيه أعمدة تحتاج مراجعة Mapping قبل الاعتماد النهائي على كل الرسومات.",
        "msg_cleaned_high_confidence": "تم تنظيف الملف وتجهيزه للتحليل بثقة عالية.",
    },
    "en": {
        "app_name": "DataBridge",
        "app_sub": "M&E Hub for Health Programs",
        "app_slogan": "Complete Monitoring & Evaluation Platform",
        "login_title": "Login",
        "username": "Username",
        "password": "Password",
        "login_btn": "Sign In",
        "login_error": "❌ Incorrect username or password",
        "logout": "Sign Out",
        "upload_label": "Upload IDUs Database (Excel)",
        "upload_hint": "📋 Upload your IDUs Database file — auto-analyzed on upload",
        "upload_hint2": "✅ The system recognizes this sheet structure and validates logical gaps automatically",
        "tab_data": "📋 Data",
        "tab_gaps": "🔍 Gap Analysis",
        "tab_stats": "📊 Statistics",
        "tab_export": "💾 Export",
        "total": "Total Beneficiaries",
        "has_followup": "With Follow-up",
        "no_followup": "No Follow-up",
        "positive": "Positive Result",
        "refused": "Refused Testing",
        "beneficiary": "beneficiary",
        "positive_case": "positive case",
        "from_total": "of total",
        "show_label": "View:",
        "all_data": "All Data",
        "without_followup": "No Follow-up",
        "with_followup": "With Follow-up",
        "positive_cases": "Positive Cases",
        "rows_count": "Row count",
        "gaps_info": "These gaps are not errors — each has a documented logical reason",
        "gaps_report": "Gap Report",
        "no_gaps": "✅ No gaps found!",
        "col_name": "Column",
        "gap_count": "Gap Count",
        "gap_pct": "Percentage %",
        "gap_reason": "Logical Reason",
        "gap_status": "Status",
        "justified": "✅ Logically Justified",
        "needs_review": "⚠️ Needs Review",
        "export_csv": "📥 Export CSV",
        "export_excel": "📥 Export Excel with Report",
        "save_excel_title": "💾 Save to Excel Sheet",
        "upload_db": "Upload IDUs Database Excel",
        "save_all_btn": "✅ Add All Records to Sheet",
        "save_success": "Saved successfully!",
        "download_updated": "⬇️ Download Updated Sheet",
        "chart_test": "Test Results",
        "chart_followup": "Follow-up Distribution",
        "chart_services": "Services Delivered",
        "chart_age": "Age Group Distribution",
        "chart_area": "Geographic Distribution — Area",
        "chart_gov": "Governorate Distribution",
        "chart_age_prot": "Protective Tools by Age Group",
        "chart_monthly": "Monthly Visits",
        "with_followup_label": "With Follow-up",
        "without_followup_label": "No Follow-up",
        "refused_test": "Refused Testing",
        "file_error": "Error loading file",
        "lang_btn": "العربية",
        "section_title": "IDUs Database — Be Frienders 2026",
        "col_reason_confirm": "Negative test or no test performed",
        "col_reason_referral": "Negative test or no test performed",
        "col_reason_test_fu": "No follow-up or no test performed",
        "col_reason_condoms_fu": "No follow-up visit",
        "col_reason_lube_fu": "No follow-up visit",
        "col_reason_syph_fu": "Refused or no follow-up",
        "col_reason_psycho_fu": "Refused or no follow-up",
        "col_reason_syr_fu": "No follow-up visit",
        "col_reason_meth_fu": "Refused or no follow-up",
        "col_reason_default": "Beneficiary refused",
        # ── Phase 2 ──
        "tab_quality": "🔎 Data Quality",
        "dq_title": "Data Quality Engine",
        "dq_subtitle": "Comprehensive record-level validation against approved business rules",
        "dq_errors": "Data Quality Errors",
        "dq_warnings": "Warnings",
        "dq_ok": "Valid Records",
        "dq_col_row": "Record #",
        "dq_col_field": "Field",
        "dq_col_value": "Value",
        "dq_col_rule": "Rule Violated",
        "dq_col_severity": "Severity",
        "dq_col_notes": "Notes",
        "dq_save_notes": "💾 Save Notes",
        "dq_notes_saved": "✅ Notes saved",
        "dq_export": "📥 Export Quality Report",
        "dq_filter_label": "Filter by severity:",
        "dq_all": "All",
        "dq_err_age": "Age outside allowed range (15-70 or defined categories)",
        "dq_err_age_u15": "Age under 15 — guardian note required",
        "dq_err_positive_referral": "Positive result without treatment referral",
        "dq_err_followup_nodate": "Follow-up data exists but no follow-up date",
        "dq_err_negative_qty": "Negative quantity not acceptable",
        "dq_err_duplicate_serial": "Duplicate serial number",
        "dq_err_duplicate_code": "Duplicate composite code",
        "dq_err_code_mismatch": "Composite code does not match birth date or governorate data",
        "dq_warn_positive_noconfirm": "Positive result without confirmatory test (rare — may be refusal)",
        "dq_err_invalid_code_format": "Composite code format is invalid",
        "dq_notes_placeholder": "Add a note...",
        "dq_no_issues": "✅ No data quality issues found!",
        "dq_run_btn": "🔍 Run Quality Check",
        "dq_show_errors_only": "🔴 Errors Only",
        "dq_show_warnings_only": "🟡 Warnings Only",
        "dq_show_all_issues": "All Issues",
        "dq_records_with_issues": "Records with Issues",
        # ── Phase 3 — Full bilingual sweep ──
        # Password change
        "change_password_btn": "🔑 Change Password",
        "current_password": "Current Password",
        "new_password": "New Password",
        "confirm_password": "Confirm Password",
        "save_btn": "Save",
        "password_mismatch": "❌ New passwords do not match",
        "pw_current_wrong": "❌ Current password is incorrect",
        "pw_new_too_short": "❌ New password must be at least 8 characters",
        "pw_new_same_as_old": "❌ New password must be different from the old one",
        "pw_changed_success": "✅ Password changed successfully",
        # Source auto-converter (upload + 204-col converter)
        "err_not_204_sheet": "This file does not appear to be the 204-column source sheet.",
        "err_no_visit_date_or_code": "Visit date or composite code not found in the source sheet.",
        "convert_upload_hint": "🔄 Upload the source sheet (204 columns) and it will be automatically converted to the program sheet structure",
        "converting_spinner": "⚙️ Converting...",
        "converted_prefix": "[Converted]",
        "convert_success": "Converted!",
        "convert_success_records": "records ready for analysis",
        "download_converted_sheet": "⬇️ Download Converted Sheet",
        "auto_converted_detected": "🔄 Detected the 204-column source sheet and converted it automatically before analysis.",
        "converted_auto_prefix": "[Auto-Converted]",
        # Smart Data Cleaner / Auto Mapper
        "smart_cleaner_title": "Smart Data Cleaner — File Validation & Cleaning",
        "mapper_confidence_title": "Auto Data Mapper — Confidence Dashboard (Before Approval)",
        "mapper_verify_sub": "85–94% likely correct",
        "mapper_suspicious_sub": "70–84% needs attention",
        "mapper_unknown_sub": "Below 70%",
        "mapper_profile_warning": "Data Profile Validation detected a suspicious mapping based on column content, not just the name.",
        "mapper_report_title": "Auto Data Mapper — Column Mapping Report",
        "mapper_profile_caption": "Once approved, the mapping will be saved to AppData/DataBridge/mapping_memory.json for future use.",
        "mapper_approved_success": "✅ Column mapping approved and saved to Mapping Memory. You can rely on the current analysis.",
        "mapper_unapprove_btn": "↩️ Cancel Approval and Re-Review",
        "mapper_review_warning": "Review the column mapping first, then click approve before the analysis and charts appear.",
        "mapper_approve_btn": "✅ Approve Mapping and Run Analysis",
        "mapper_approve_btn_with_review": "✅ Approve Mapping Despite",
        "cleaner_missing_core_error": "Core columns are missing. Review the report before relying on the numbers.",
        "cleaner_warnings_warning": "The file was cleaned, but there are warnings that may affect month filters or some charts.",
        "cleaner_success": "File cleaned and ready for analysis.",
        "analysis_paused_info": "⏸️ Analysis is paused until the column mapping is approved from the Auto Data Mapper report above.",
        # Records-displayed info box
        "records_displayed": "Records Displayed",
        "of_total": "of total",
        # Compact summary table labels
        "tbl_count": "Count",
        "tbl_reach": "Reach",
        "tbl_men": "Men",
        "tbl_followup": "Follow-up",
        "tbl_syringes": "Syringes",
        "tbl_followup_syringes": "Follow-up Syringes",
        "tbl_lubricants": "Lubricants",
        "tbl_followup_lubricant": "Follow-up Lubricant",
        "tbl_condoms": "Condoms",
        "tbl_followup_condom": "Follow-up Condom",
        "tbl_total_tests": "Total Tests",
        "tbl_negative": "Negative",
        "tbl_positive": "Positive",
        "tbl_not_available": "Not Available",
        "tbl_confirmatory_positive": "Confirmatory Positive",
        "tbl_psycho_support": "Psychological Support",
        "tbl_syphilis": "Syphilis",
        "tbl_item": "Item",
        # Summary tab labels
        "summary_tab_month_prefix": "📋 Summary for",
        "summary_tab_default": "📋 Data Summary",
        # Tab names
        "tab_repair": "🛠 Data Repair Center",
        "tab_indicators": "📈 Indicators",
        "tab_ai": "🤖 AI Assistant",
        "tab_settings": "⚙️ Settings",
        "tab_converter": "🔄 Source Converter",
        # Chart axis/legend labels
        "chart_label_result": "Result",
        "chart_label_count": "Count",
        "chart_label_status": "Status",
        "chart_label_service": "Service",
        "chart_label_age_group": "Age Group",
        "chart_label_area": "Area",
        "chart_label_governorate": "Governorate",
        "chart_label_tool": "Tool",
        "chart_label_month": "Month",
        "chart_label_visit_count": "Visit Count",
        # Service/intervention category labels (chart series names)
        "svc_syphilis": "Syphilis",
        "svc_psycho_support": "Psychological Support",
        "svc_methadone": "Methadone",
        "svc_condoms": "Condoms",
        "svc_lubricants": "Lubricants",
        "svc_syringes": "Syringes",
        # Period / export labels
        "period_to": "to",
        "period_all": "All Period",
        "period_summary_caption": "Period Summary",
        "download_summary_excel": "⬇️ Download Data Summary Excel",
        "summary_filename_prefix": "Data_Summary",
        # Data Quality tab
        "dq_running_spinner": "🔍 Running check...",
        "dq_run_prompt": "Click the check button to run the data quality engine on {n} records",
        "dq_total_issues": "Total Issues",
        "dq_col_serial": "Serial",
        "dq_under15_notice": "🔴 The following records need a guardian note:",
        "dq_record_label": "Record #{row} — Serial {serial} — Age: {age}",
        "dq_severity_error": "Error",
        "dq_severity_warning": "Warning",
        "dq_download_report": "⬇️ Download Quality Report",
        # Indicators tab
        "indicators_subtitle": "Actual achievement of program indicators",
        "targets_subtitle": "Enter targets from Global Fund — Annual + Q1/Q2/Q3/Q4",
        # Reports / AI Assistant tab
        "generating_reports_spinner": "⚙️ Generating reports...",
        "download_report_ar": "⬇️ Arabic Report (.docx)",
        "download_report_en": "⬇️ English Report (.docx)",
        "reports_generated_success": "✅ Both reports generated!",
        "ai_assistant_subtitle": "An AI assistant specialized in M&E — writes reports and analyzes data",
        # Settings tab
        "settings_subtitle": "App settings — saved automatically in AppData / DataBridge",
        "get_free_key_from": "Get your free key from:",
        "settings_saved_in": "Settings are saved in:",
        "api_key_saved": "✅ Key saved",
        "ai_provider_help": "Currently Gemini only; OpenAI or a Local LLM may be added later.",
        "fallback_model_warning": "⚠️ The selected model is unavailable, but the connection succeeded using fallback: {model}",
        "model_not_available_error": "❌ Model not available. Try selecting a different model from settings.",
        "app_info_title": "App Information",
        # Source Converter tab
        "converter_tab_subtitle": "Automatically convert the source sheet (204 columns) to the program sheet (27 columns)",
        "converter_tab_hint": "Upload the source sheet (204 columns) and it will be automatically converted to the program sheet structure, ready for analysis.",
        "upload_source_sheet_excel": "Upload Source Sheet (Excel)",
        "file_label": "File",
        "columns_label": "columns",
        "convert_now_btn": "🔄 Convert Now",
        "convert_clean_success": "Converted and cleaned!",
        "convert_clean_records": "records",
        "converter_auto_mapper_title": "Auto Mapper for the converted file — review the mapping before approval",
        "use_converted_btn": "✅ Use the converted file for analysis and open the approval screen",
        "convert_error": "Conversion error",
        # Data Repair Center
        "data_updated_info": "Data updated in this session. The analysis will reload now.",
        "repair_center_title": "🛠 Data Repair Center",
        "repair_caption": "All repairs here require your approval. No automatic fill or guessing is performed on the entire file.",
        "repair_no_examples": "✅ No clear error examples in dates/quantities/yes-no fields.",
        "repair_no_suggestions": "No repairs suggested currently.",
        "repair_forbidden_warning": "🚫 Automatic repair is forbidden for sensitive fields: Visit Date / Follow-up Date / HIV Result / Referral / Gender / Age / Beneficiary Code. Only readable dates are converted, without filling or guessing.",
        "repair_applied_success": "✅ Only the selected repairs were applied.",
        # data_cleaner.py report tables
        "rpt_col_check": "Check",
        "rpt_col_result": "Result",
        "rpt_col_type": "Type",
        "rpt_check_status": "Check Status",
        "rpt_detected_sheet": "Detected Sheet",
        "rpt_first_or_selected": "First/Selected",
        "rpt_rows_before": "Rows Before Cleaning",
        "rpt_cols_before": "Columns Before Cleaning",
        "rpt_rows_after": "Rows After Cleaning",
        "rpt_cols_after": "Columns After Cleaning",
        "rpt_memory_usage": "Memory Usage (MB)",
        "rpt_detected_header_row": "Detected Header Row",
        "rpt_sheet_ranking": "Sheet Ranking",
        "rpt_mapping_result": "Auto Mapping Result",
        "rpt_missing_core_cols": "Missing Core Columns",
        "rpt_missing_optional_cols": "Missing Optional Columns",
        "rpt_invalid_dates_in": "Invalid dates in {col}",
        "rpt_negative_qty_in": "Negative/invalid quantities in {col}",
        "rpt_empty_rows_dropped": "Empty Rows Dropped",
        "rpt_standard_df_summary": "{rows} rows × {cols} columns",
        "rpt_note": "Note",
        "rpt_col_original": "Original Column",
        "rpt_col_canonical": "Canonical Column",
        "rpt_col_confidence": "Confidence",
        "rpt_col_method": "Method",
        # data_cleaner.py dynamic notes/warnings/errors
        "msg_high_memory": "Memory usage is high; charts and export may be slower than usual.",
        "msg_incomplete_analysis": "The analysis may be incomplete due to missing core columns.",
        "msg_dates_converted_blank": "Invalid dates were converted to blank and will not be included in month filters.",
        "msg_qty_converted_blank": "Non-numeric quantities were converted to blank, and negative quantities are shown in the report.",
        "msg_profile_validation_suspicious": "Data Profile Validation detected a suspicious mapping based on column content.",
        "msg_mapping_needs_review": "There are columns that need Mapping review before final reliance on all charts.",
        "msg_cleaned_high_confidence": "The file was cleaned and prepared for analysis with high confidence.",
    }
}


